In [1]:
import numpy as np

# Define the 4 vectors to be stored
vectors = np.array([[1, 1, -1, -1],
                    [-1, -1, 1, 1],
                    [1, -1, 1, -1],
                    [-1, 1, -1, 1]])

# Calculate the weight matrix using Hebbian learning rule
num_vectors = vectors.shape[0]
weights = np.zeros((4, 4))
for i in range(num_vectors):
    for j in range(num_vectors):
        if i != j:
            weights += np.outer(vectors[i], vectors[j])

# Normalize the weights matrix (excluding the diagonal)
np.fill_diagonal(weights, 0)

# Define the activation function (in this case, a sign function)
def activation(x):
    return np.where(x >= 0, 1, -1)

# Define the Hopfield network function (asynchronous update)
def hopfield(input_vector, weights, max_iterations=10):
    output_vector = input_vector.copy()
    for _ in range(max_iterations):
        # Asynchronously update the network
        for i in range(len(output_vector)):
            net_input = np.dot(weights[i], output_vector)
            output_vector[i] = activation(net_input)
    return output_vector

# Test the Hopfield network with one of the stored vectors as input
input_vector = vectors[0]
output_vector = hopfield(input_vector, weights)

print("Input vector:")
print(input_vector)
print("Output vector:")
print(output_vector)


Input vector:
[ 1  1 -1 -1]
Output vector:
[-1 -1 -1 -1]


In [3]:
import numpy as np

# Define the 4 vectors to be stored
vectors = np.array([[1, 1, -1, -1],
                    [-1, -1, 1, 1],
                    [1, -1, 1, -1],
                    [-1, 1, -1, 1]])

# Calculate the weight matrix using Hebbian learning rule
num_vectors = vectors.shape[0]
weights = np.zeros((4, 4))
for i in range(num_vectors):
    for j in range(num_vectors):
        if i != j:
            weights += np.outer(vectors[i], vectors[j])

# Normalize the weights matrix (excluding the diagonal)
np.fill_diagonal(weights, 0)

# Define the activation function (in this case, a sign function)
def activation(x):
    return np.where(x >= 0, 1, -1)

# Define the Hopfield network function (asynchronous update)
def hopfield(input_vector, weights, max_iterations=10):
    output_vector = input_vector.copy()
    prev_output = np.zeros_like(output_vector)
    
    # Asynchronous update loop until convergence or max_iterations
    iteration = 0
    while not np.array_equal(output_vector, prev_output) and iteration < max_iterations:
        prev_output = output_vector.copy()
        for i in range(len(output_vector)):
            net_input = np.dot(weights[i], output_vector)
            output_vector[i] = activation(net_input)
        iteration += 1
        
    return output_vector

# Test the Hopfield network with one of the stored vectors as input
input_vector = vectors[0]  # Choose the first vector from stored vectors
output_vector = hopfield(input_vector, weights)

print("Input vector:")
print(input_vector)
print("Output vector:")
print(output_vector)


Input vector:
[ 1  1 -1 -1]
Output vector:
[-1 -1 -1 -1]


In [5]:
import numpy as np

# Define the 4 vectors to be stored
vectors = np.array([[1, 1, -1, -1],
                    [-1, -1, 1, 1],
                    [1, -1, 1, -1],
                    [-1, 1, -1, 1]])

# Calculate the weight matrix using Hebbian learning rule
num_vectors = vectors.shape[0]
weights = np.zeros((4, 4))
for i in range(num_vectors):
    for j in range(num_vectors):
        if i != j:
            weights += np.outer(vectors[i], vectors[j])

# Normalize the weights matrix (excluding the diagonal)
np.fill_diagonal(weights, 0)

# Define the activation function (in this case, a sign function)
def activation(x):
    return np.where(x >= 0, 1, -1)

# Define the Hopfield network function (asynchronous update)
def hopfield(input_vector, weights, max_iterations=10):
    output_vector = input_vector.copy()
    for _ in range(max_iterations):
        # Asynchronously update the network
        for i in range(len(output_vector)):
            net_input = np.dot(weights[i], output_vector)
            output_vector[i] = activation(net_input)
    return output_vector

# Test the Hopfield network with one of the stored vectors as input
input_vector = vectors[0]
output_vector = hopfield(input_vector, weights)

print("Input vector:")
print(input_vector)
print("Output vector:")
print(output_vector)


Input vector:
[ 1  1 -1 -1]
Output vector:
[-1 -1 -1 -1]
